name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest  # Где запускаем
    steps: # Что делаем
      - uses: actions/checkout@v4 # Выкачиваем репозиторий
      - uses: actions/setup-java@v4 # Настраиваем Java
        with:
          distribution: 'oracle' # Указываем название поставщика JDK
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test # запуск тестов



